<a href="https://colab.research.google.com/github/Xalphanos/Pytorch_Basics/blob/main/Pytorch_tutorialspoint_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
import matplotlib.pyplot as plt
import pandas as pd
print(torch.__version__)


2.8.0+cu126


### Introduction to Tensors

we intorduce it by using syntax torch.tensor(7)



In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
# to find the dimensions of the tensor given to us


0

In [5]:
scalar.item()

7

In [6]:
matrix=torch.tensor([[1,2],
                     [3,4]])
print(matrix.shape)
print(matrix.ndim)


torch.Size([2, 2])
2


In [7]:
#Tensor

TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
print(TENSOR.ndim)
print(TENSOR.shape)


3
torch.Size([1, 3, 3])


### Random tensors

Random tensors importent beaucse the way neural networks learn is that they start with tensors full of random numbers and then adjust those random number to better represent the data

In [8]:
# Create a random tensor of size (2,4)

random_tensor=torch.rand(10,10,4)
random_tensor

tensor([[[7.4623e-01, 6.5135e-01, 8.6408e-01, 1.3570e-01],
         [6.4711e-01, 5.3953e-01, 4.6403e-01, 2.2850e-01],
         [3.2851e-02, 1.5912e-01, 8.5055e-02, 8.8389e-01],
         [3.0625e-02, 5.5771e-01, 6.1790e-01, 5.1645e-01],
         [2.6625e-01, 8.4033e-01, 6.4726e-01, 4.4459e-02],
         [1.9629e-01, 5.5865e-01, 1.9071e-02, 2.4798e-01],
         [1.7406e-01, 8.2733e-01, 4.9149e-01, 3.0468e-01],
         [8.0871e-01, 9.4898e-01, 2.7481e-01, 4.9081e-01],
         [9.4402e-02, 9.4217e-01, 8.5931e-01, 2.1056e-01],
         [2.9485e-01, 2.6809e-01, 9.1657e-01, 8.1117e-01]],

        [[2.5288e-01, 5.8054e-01, 4.7315e-01, 6.2538e-02],
         [3.6880e-01, 8.7879e-01, 4.4597e-01, 8.5607e-01],
         [5.5988e-01, 6.2509e-01, 1.9637e-01, 6.2810e-01],
         [6.6885e-01, 4.2545e-01, 6.3575e-01, 1.4418e-01],
         [7.8739e-01, 9.4879e-02, 2.4515e-01, 6.3625e-01],
         [4.0807e-01, 8.6360e-01, 3.1356e-01, 7.8210e-01],
         [1.1799e-01, 6.3359e-01, 2.7773e-01, 4.2566e-

In [9]:
random_tensor.ndim


3

In [10]:
# Create a random tensor with similar shape to an image tensor

random_image_tensor=torch.rand(size=(224,224,3))#height, width and color channels RG and B
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([224, 224, 3])
3


In [11]:
rand1=torch.rand(size=(3,4,56,7))
rand1.ndim

4

In [12]:
rand1.shape

torch.Size([3, 4, 56, 7])

# Creating a range of tensors and similar

In [13]:
one_2_ten=torch.arange(1,11)
one_2_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
sequence=torch.arange(start=0,end=1000,step=90)
sequence

tensor([  0,  90, 180, 270, 360, 450, 540, 630, 720, 810, 900, 990])

In [15]:
#tensor-like
ten_zeroes=torch.ones_like(input=sequence)
ten_zeroes

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes


In [16]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                             device=None,#what device your tensor is on
                             requires_grad=False)# if we are tracking the gradients of the tensor or not)

In [17]:
float_32_tensor.dtype

torch.float32

In [18]:
float_16_tensor= float_32_tensor.type(torch.float16)# converting the tensor from 32 to float 16

In [19]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Tensor multiplication

In [20]:

sometensor=torch.rand(3,4)
sometensor

tensor([[0.6718, 0.4537, 0.1077, 0.3926],
        [0.7226, 0.0328, 0.8045, 0.7033],
        [0.4793, 0.9714, 0.8635, 0.2978]])

In [21]:
print(sometensor)
print(f"Datatype of tensor: {sometensor.dtype}")
print(f"Shape of tensor: {sometensor.shape}")
print(f"Device tensor is on: {sometensor.device}")

tensor([[0.6718, 0.4537, 0.1077, 0.3926],
        [0.7226, 0.0328, 0.8045, 0.7033],
        [0.4793, 0.9714, 0.8635, 0.2978]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# We will do some airthmetic operations on the tensor


In [22]:
tensor=torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [23]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [24]:
torch.mul(tensor,11)

tensor([110, 220, 330])

# Most importent basic concepts of these couse that is natrix multiplication basically whole of the couse is based on that so please pay a little bit attendtion to what matrix multiplication actually is


In [25]:
# Element wise multipliction
tensor

tensor([10, 20, 30])

In [26]:
print(f"element wise multiplication equals: {tensor * tensor}")

element wise multiplication equals: tensor([100, 400, 900])


In [27]:
#Matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 741 µs, total: 741 µs
Wall time: 16.5 ms


tensor(1400)

In [28]:
%%time
value=0 # SEE THE DIFFERENCE IN TIME WHEN USING DIFFERENT ELEMENTS
for i in range(len(tensor)):
  value+= tensor[i]* tensor[i]
print(value)


tensor(1400)
CPU times: user 1.41 ms, sys: 0 ns, total: 1.41 ms
Wall time: 1.41 ms


In [29]:
#shapes for matrix multiplicatijon


tensor_A=torch.tensor([[1,3],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[1,3],
                      [3,4],
                      [5,6]])

torch.matmul(tensor_A.T, tensor_B)


tensor([[35, 45],
        [45, 61]])

#Findinghte min, max, sum etc(tensor operations and aggregation)

In [30]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
print(f"the min value is {torch.min(x)}")
print(f"the max value is {torch.max(x)}")
print(f"the mean value is {torch.mean(x.type(torch.float32))}")
print(f"the mean value is {torch.sum(x)}")

# mean requires a float32 datatype to work


the min value is 0
the max value is 90
the mean value is 45.0
the mean value is 450


In [32]:
print(f"the  positonal min value is {torch.argmin(x)}")# positional tensor whch has the least value

the  positonal min value is 0


In [33]:
x.argmax()

tensor(9)

## Reshaping ,stacking, squeezing and unsqueezing tensors

* Reshaping an input tensor to a desired shape
* View= viewing that tensor from a different perspective or an angle

* Stacking = combining multiple tensors in top of each other (vertical stack) or side by side (horizontal stack)

* Squeeze - Removes alll '1' dimensions from a tensor

* Unsqueeze - adds a '1' dimension to a target tensor

* Permute- Return a view of the input with the dimensions permutted(swapped) in a certain way.



In [34]:
# creating and working on the tensor

import torch
x=torch.arange(0.,10.)

x , x.shape,x.ndim

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]), 1)

In [35]:
x_reshaped=x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [36]:
x_reshaped=x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [37]:
#change the shape


x_reshaped=x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 torch.Size([2, 5]))

In [38]:
# change the view

z=x.view(1,10)
z[:,0]=5
z,z.shape


(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [39]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9.]])

In [40]:
#torch.squeeze removes the dim 1 from all the tensors
x_reshape=x_reshaped.reshape(1,10)

In [41]:
x_reshape.shape

torch.Size([1, 10])

In [42]:
x_reshape=x_reshape.squeeze(dim=0)

In [43]:
# unsqueeze adds a single dim to a sqeezed sensor
prev_tensor=x_reshape
unsqueezed_tensor=prev_tensor.unsqueeze(dim=0)

print(f"befroe unsqueezing {prev_tensor.shape} after it {unsqueezed_tensor.shape} ")


befroe unsqueezing torch.Size([10]) after it torch.Size([1, 10]) 


In [44]:
x_original= torch.rand(size=(224,224,3))

x_permuted=x_original.permute(2,0,1)

print(f"x_original{x_original.shape} x_permuted {x_permuted.shape}")

x_originaltorch.Size([224, 224, 3]) x_permuted torch.Size([3, 224, 224])


# Indexing done on the tensors this will likely be an east topic comparitively


In [45]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [46]:
y=torch.arange(1,28).reshape(3,3,3)
y,y.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [47]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[0][0]

tensor([1, 2, 3])

In [49]:
x[0][0][0]

tensor(1)

In [50]:
x[:,:,1]

tensor([[2, 5, 8]])

In [51]:
x[:,1,1]

tensor([5])

In [52]:
x[0,0,:]

tensor([1, 2, 3])

# pytorch tensors and nyumpy

scientific python numerical computing library



In [53]:
import torch
import numpy as np

array= np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)# when coverting from numpy to pytorch, pytorch reflects numpys default datatype float64

array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [54]:
tensor.dtype

torch.float32

In [55]:
#change the vlaue of array
array=array+1
array, tensor# tnesor remains unchanged from the original array


(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
# now reversing the roles we go from tensor to numpy

tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
numpy_tensor.dtype

dtype('float32')

In [59]:
#change the tensor, what happens to numpy tensor
tensor= tensor+1
tensor,numpy_tensor# same behaviour as the previous one

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducability in pytorch
trying to take out the random out of random
In short how a neural network works
* start with random numbers -> tensor operations -> update those random numbers to make them similar to the desired output -> again -> again -> again

to reduce randomness comes the concept of random seed

Essentially what random seed does is "flavor" the randomness



In [60]:
import torch

random_tensorA=torch.rand(3,4)
random_tensorB=torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)



tensor([[0.0305, 0.9722, 0.0358],
        [0.2017, 0.4095, 0.0434],
        [0.8630, 0.3056, 0.3245]])